<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::statement('ALTER SEQUENCE "clientes_tasca_id_seq" RENAME TO "clientes_tienda_id_seq"');
        DB::statement('ALTER SEQUENCE "productos_tasca_id_seq" RENAME TO "productos_tienda_id_seq"');
        DB::statement('ALTER SEQUENCE "ventas_tasca_id_seq" RENAME TO "ventas_tienda_id_seq"');
        DB::statement('ALTER SEQUENCE "ventas_tasca_detalles_id_seq" RENAME TO "ventas_tienda_detalles_id_seq"');
        DB::statement('ALTER SEQUENCE "pagos_tasca_id_seq" RENAME TO "pagos_tienda_id_seq"');
        DB::statement('ALTER SEQUENCE "pago_venta_tasca_id_seq" RENAME TO "pago_venta_tienda_id_seq"');
        DB::statement('ALTER SEQUENCE "insumos_tasca_id_seq" RENAME TO "insumos_tienda_id_seq"');
        DB::statement('ALTER SEQUENCE "lotes_tasca_id_seq" RENAME TO "lotes_tienda_id_seq"');
        DB::statement('ALTER SEQUENCE "compras_tasca_id_seq" RENAME TO "compras_tienda_id_seq"');
        DB::statement('ALTER SEQUENCE "proveedores_tasca_id_seq" RENAME TO "proveedores_tienda_id_seq"');
        DB::statement('ALTER SEQUENCE "gastos_tasca_id_seq" RENAME TO "gastos_tienda_id_seq"');
        DB::statement('ALTER INDEX "clientes_tasca_pkey" RENAME TO "clientes_tienda_pkey"');
        DB::statement('ALTER INDEX "productos_tasca_pkey" RENAME TO "productos_tienda_pkey"');
        DB::statement('ALTER INDEX "productos_tasca_codigo_barras_unique" RENAME TO "productos_tienda_codigo_barras_unique"');
        DB::statement('ALTER INDEX "ventas_tasca_pkey" RENAME TO "ventas_tienda_pkey"');
        DB::statement('ALTER INDEX "ventas_tasca_detalles_pkey" RENAME TO "ventas_tienda_detalles_pkey"');
        DB::statement('ALTER INDEX "pagos_tasca_pkey" RENAME TO "pagos_tienda_pkey"');
        DB::statement('ALTER INDEX "pago_venta_tasca_pkey" RENAME TO "pago_venta_tienda_pkey"');
        DB::statement('ALTER INDEX "insumos_tasca_pkey" RENAME TO "insumos_tienda_pkey"');
        DB::statement('ALTER INDEX "lotes_tasca_pkey" RENAME TO "lotes_tienda_pkey"');
        DB::statement('ALTER INDEX "compras_tasca_pkey" RENAME TO "compras_tienda_pkey"');
        DB::statement('ALTER INDEX "proveedores_tasca_pkey" RENAME TO "proveedores_tienda_pkey"');
        DB::statement('ALTER INDEX "gastos_tasca_pkey" RENAME TO "gastos_tienda_pkey"');
        DB::statement('ALTER TABLE "clientes_tienda" RENAME CONSTRAINT "clientes_tasca_id_not_null" TO "clientes_tienda_id_not_null"');
        DB::statement('ALTER TABLE "clientes_tienda" RENAME CONSTRAINT "clientes_tasca_nombre_not_null" TO "clientes_tienda_nombre_not_null"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tasca_id_not_null" TO "productos_tienda_id_not_null"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tasca_nombre_not_null" TO "productos_tienda_nombre_not_null"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tasca_precio_not_null" TO "productos_tienda_precio_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_id_not_null" TO "ventas_tienda_id_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_total_not_null" TO "ventas_tienda_total_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_descuento_not_null" TO "ventas_tienda_descuento_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_estado_not_null" TO "ventas_tienda_estado_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_fecha_not_null" TO "ventas_tienda_fecha_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_id_cliente_tasca_foreign" TO "ventas_tienda_id_cliente_tienda_foreign"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_id_cliente_miembro_foreign" TO "ventas_tienda_id_cliente_miembro_foreign"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tasca_detalles_id_not_null" TO "ventas_tienda_detalles_id_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tasca_detalles_id_venta_not_null" TO "ventas_tienda_detalles_id_venta_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tasca_detalles_id_producto_not_null" TO "ventas_tienda_detalles_id_producto_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tasca_detalles_precio_unitario_not_null" TO "ventas_tienda_detalles_precio_unitario_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tasca_detalles_subtotal_not_null" TO "ventas_tienda_detalles_subtotal_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tasca_detalles_id_venta_foreign" TO "ventas_tienda_detalles_id_venta_foreign"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tasca_detalles_id_producto_foreign" TO "ventas_tienda_detalles_id_producto_foreign"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tasca_id_not_null" TO "pagos_tienda_id_not_null"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tasca_monto_usd_not_null" TO "pagos_tienda_monto_usd_not_null"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tasca_tasa_not_null" TO "pagos_tienda_tasa_not_null"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tasca_metodo_pago_not_null" TO "pagos_tienda_metodo_pago_not_null"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tasca_fecha_pago_not_null" TO "pagos_tienda_fecha_pago_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tasca_id_not_null" TO "pago_venta_tienda_id_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tasca_id_pago_not_null" TO "pago_venta_tienda_id_pago_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tasca_id_venta_not_null" TO "pago_venta_tienda_id_venta_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tasca_monto_abonado_usd_not_null" TO "pago_venta_tienda_monto_abonado_usd_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tasca_id_pago_foreign" TO "pago_venta_tienda_id_pago_foreign"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tasca_id_venta_foreign" TO "pago_venta_tienda_id_venta_foreign"');
        DB::statement('ALTER TABLE "insumos_tienda" RENAME CONSTRAINT "insumos_tasca_id_not_null" TO "insumos_tienda_id_not_null"');
        DB::statement('ALTER TABLE "insumos_tienda" RENAME CONSTRAINT "insumos_tasca_nombre_not_null" TO "insumos_tienda_nombre_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_id_not_null" TO "lotes_tienda_id_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_id_insumo_not_null" TO "lotes_tienda_id_insumo_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_cantidad_comprada_not_null" TO "lotes_tienda_cantidad_comprada_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_costo_unitario_not_null" TO "lotes_tienda_costo_unitario_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_stock_actual_not_null" TO "lotes_tienda_stock_actual_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_fecha_compra_not_null" TO "lotes_tienda_fecha_compra_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_estado_not_null" TO "lotes_tienda_estado_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_id_insumo_foreign" TO "lotes_tienda_id_insumo_foreign"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_proveedor_id_foreign" TO "lotes_tienda_proveedor_id_foreign"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tasca_id_insumo_foreign" TO "productos_tienda_id_insumo_foreign"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tasca_medida_descuento_not_null" TO "productos_tienda_medida_descuento_not_null"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tasca_id_not_null" TO "compras_tienda_id_not_null"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tasca_fecha_compra_not_null" TO "compras_tienda_fecha_compra_not_null"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tasca_total_usd_not_null" TO "compras_tienda_total_usd_not_null"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tasca_estado_not_null" TO "compras_tienda_estado_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tasca_compra_id_foreign" TO "lotes_tienda_compra_id_foreign"');
        DB::statement('ALTER TABLE "proveedores_tienda" RENAME CONSTRAINT "proveedores_tasca_id_not_null" TO "proveedores_tienda_id_not_null"');
        DB::statement('ALTER TABLE "proveedores_tienda" RENAME CONSTRAINT "proveedores_tasca_nombre_not_null" TO "proveedores_tienda_nombre_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tasca_id_not_null" TO "gastos_tienda_id_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tasca_categoria_not_null" TO "gastos_tienda_categoria_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tasca_descripcion_not_null" TO "gastos_tienda_descripcion_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tasca_monto_usd_not_null" TO "gastos_tienda_monto_usd_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tasca_metodo_pago_not_null" TO "gastos_tienda_metodo_pago_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tasca_fecha_not_null" TO "gastos_tienda_fecha_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tasca_proveedor_id_foreign" TO "gastos_tienda_proveedor_id_foreign"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tasca_compra_id_foreign" TO "gastos_tienda_compra_id_foreign"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tasca_proveedor_id_foreign" TO "compras_tienda_proveedor_id_foreign"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tasca_abono_usd_not_null" TO "compras_tienda_abono_usd_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_id_autorizador_foreign" TO "ventas_tienda_id_autorizador_foreign"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_id_persona_foreign" TO "ventas_tienda_id_persona_foreign"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tasca_tipo_not_null" TO "productos_tienda_tipo_not_null"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tasca_tipo_check" TO "productos_tienda_tipo_check"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tasca_detalles_cantidad_not_null" TO "ventas_tienda_detalles_cantidad_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tasca_cargo_servicio_not_null" TO "ventas_tienda_cargo_servicio_not_null"');
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        DB::statement('ALTER SEQUENCE "clientes_tienda_id_seq" RENAME TO "clientes_tasca_id_seq"');
        DB::statement('ALTER SEQUENCE "productos_tienda_id_seq" RENAME TO "productos_tasca_id_seq"');
        DB::statement('ALTER SEQUENCE "ventas_tienda_id_seq" RENAME TO "ventas_tasca_id_seq"');
        DB::statement('ALTER SEQUENCE "ventas_tienda_detalles_id_seq" RENAME TO "ventas_tasca_detalles_id_seq"');
        DB::statement('ALTER SEQUENCE "pagos_tienda_id_seq" RENAME TO "pagos_tasca_id_seq"');
        DB::statement('ALTER SEQUENCE "pago_venta_tienda_id_seq" RENAME TO "pago_venta_tasca_id_seq"');
        DB::statement('ALTER SEQUENCE "insumos_tienda_id_seq" RENAME TO "insumos_tasca_id_seq"');
        DB::statement('ALTER SEQUENCE "lotes_tienda_id_seq" RENAME TO "lotes_tasca_id_seq"');
        DB::statement('ALTER SEQUENCE "compras_tienda_id_seq" RENAME TO "compras_tasca_id_seq"');
        DB::statement('ALTER SEQUENCE "proveedores_tienda_id_seq" RENAME TO "proveedores_tasca_id_seq"');
        DB::statement('ALTER SEQUENCE "gastos_tienda_id_seq" RENAME TO "gastos_tasca_id_seq"');
        DB::statement('ALTER INDEX "clientes_tienda_pkey" RENAME TO "clientes_tasca_pkey"');
        DB::statement('ALTER INDEX "productos_tienda_pkey" RENAME TO "productos_tasca_pkey"');
        DB::statement('ALTER INDEX "productos_tienda_codigo_barras_unique" RENAME TO "productos_tasca_codigo_barras_unique"');
        DB::statement('ALTER INDEX "ventas_tienda_pkey" RENAME TO "ventas_tasca_pkey"');
        DB::statement('ALTER INDEX "ventas_tienda_detalles_pkey" RENAME TO "ventas_tasca_detalles_pkey"');
        DB::statement('ALTER INDEX "pagos_tienda_pkey" RENAME TO "pagos_tasca_pkey"');
        DB::statement('ALTER INDEX "pago_venta_tienda_pkey" RENAME TO "pago_venta_tasca_pkey"');
        DB::statement('ALTER INDEX "insumos_tienda_pkey" RENAME TO "insumos_tasca_pkey"');
        DB::statement('ALTER INDEX "lotes_tienda_pkey" RENAME TO "lotes_tasca_pkey"');
        DB::statement('ALTER INDEX "compras_tienda_pkey" RENAME TO "compras_tasca_pkey"');
        DB::statement('ALTER INDEX "proveedores_tienda_pkey" RENAME TO "proveedores_tasca_pkey"');
        DB::statement('ALTER INDEX "gastos_tienda_pkey" RENAME TO "gastos_tasca_pkey"');
        DB::statement('ALTER TABLE "clientes_tienda" RENAME CONSTRAINT "clientes_tienda_id_not_null" TO "clientes_tasca_id_not_null"');
        DB::statement('ALTER TABLE "clientes_tienda" RENAME CONSTRAINT "clientes_tienda_nombre_not_null" TO "clientes_tasca_nombre_not_null"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tienda_id_not_null" TO "productos_tasca_id_not_null"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tienda_nombre_not_null" TO "productos_tasca_nombre_not_null"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tienda_precio_not_null" TO "productos_tasca_precio_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_id_not_null" TO "ventas_tasca_id_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_total_not_null" TO "ventas_tasca_total_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_descuento_not_null" TO "ventas_tasca_descuento_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_estado_not_null" TO "ventas_tasca_estado_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_fecha_not_null" TO "ventas_tasca_fecha_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_id_cliente_tienda_foreign" TO "ventas_tasca_id_cliente_tasca_foreign"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_id_cliente_miembro_foreign" TO "ventas_tasca_id_cliente_miembro_foreign"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tienda_detalles_id_not_null" TO "ventas_tasca_detalles_id_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tienda_detalles_id_venta_not_null" TO "ventas_tasca_detalles_id_venta_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tienda_detalles_id_producto_not_null" TO "ventas_tasca_detalles_id_producto_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tienda_detalles_precio_unitario_not_null" TO "ventas_tasca_detalles_precio_unitario_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tienda_detalles_subtotal_not_null" TO "ventas_tasca_detalles_subtotal_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tienda_detalles_id_venta_foreign" TO "ventas_tasca_detalles_id_venta_foreign"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tienda_detalles_id_producto_foreign" TO "ventas_tasca_detalles_id_producto_foreign"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tienda_id_not_null" TO "pagos_tasca_id_not_null"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tienda_monto_usd_not_null" TO "pagos_tasca_monto_usd_not_null"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tienda_tasa_not_null" TO "pagos_tasca_tasa_not_null"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tienda_metodo_pago_not_null" TO "pagos_tasca_metodo_pago_not_null"');
        DB::statement('ALTER TABLE "pagos_tienda" RENAME CONSTRAINT "pagos_tienda_fecha_pago_not_null" TO "pagos_tasca_fecha_pago_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tienda_id_not_null" TO "pago_venta_tasca_id_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tienda_id_pago_not_null" TO "pago_venta_tasca_id_pago_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tienda_id_venta_not_null" TO "pago_venta_tasca_id_venta_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tienda_monto_abonado_usd_not_null" TO "pago_venta_tasca_monto_abonado_usd_not_null"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tienda_id_pago_foreign" TO "pago_venta_tasca_id_pago_foreign"');
        DB::statement('ALTER TABLE "pago_venta_tienda" RENAME CONSTRAINT "pago_venta_tienda_id_venta_foreign" TO "pago_venta_tasca_id_venta_foreign"');
        DB::statement('ALTER TABLE "insumos_tienda" RENAME CONSTRAINT "insumos_tienda_id_not_null" TO "insumos_tasca_id_not_null"');
        DB::statement('ALTER TABLE "insumos_tienda" RENAME CONSTRAINT "insumos_tienda_nombre_not_null" TO "insumos_tasca_nombre_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_id_not_null" TO "lotes_tasca_id_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_id_insumo_not_null" TO "lotes_tasca_id_insumo_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_cantidad_comprada_not_null" TO "lotes_tasca_cantidad_comprada_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_costo_unitario_not_null" TO "lotes_tasca_costo_unitario_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_stock_actual_not_null" TO "lotes_tasca_stock_actual_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_fecha_compra_not_null" TO "lotes_tasca_fecha_compra_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_estado_not_null" TO "lotes_tasca_estado_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_id_insumo_foreign" TO "lotes_tasca_id_insumo_foreign"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_proveedor_id_foreign" TO "lotes_tasca_proveedor_id_foreign"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tienda_id_insumo_foreign" TO "productos_tasca_id_insumo_foreign"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tienda_medida_descuento_not_null" TO "productos_tasca_medida_descuento_not_null"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tienda_id_not_null" TO "compras_tasca_id_not_null"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tienda_fecha_compra_not_null" TO "compras_tasca_fecha_compra_not_null"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tienda_total_usd_not_null" TO "compras_tasca_total_usd_not_null"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tienda_estado_not_null" TO "compras_tasca_estado_not_null"');
        DB::statement('ALTER TABLE "lotes_tienda" RENAME CONSTRAINT "lotes_tienda_compra_id_foreign" TO "lotes_tasca_compra_id_foreign"');
        DB::statement('ALTER TABLE "proveedores_tienda" RENAME CONSTRAINT "proveedores_tienda_id_not_null" TO "proveedores_tasca_id_not_null"');
        DB::statement('ALTER TABLE "proveedores_tienda" RENAME CONSTRAINT "proveedores_tienda_nombre_not_null" TO "proveedores_tasca_nombre_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tienda_id_not_null" TO "gastos_tasca_id_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tienda_categoria_not_null" TO "gastos_tasca_categoria_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tienda_descripcion_not_null" TO "gastos_tasca_descripcion_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tienda_monto_usd_not_null" TO "gastos_tasca_monto_usd_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tienda_metodo_pago_not_null" TO "gastos_tasca_metodo_pago_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tienda_fecha_not_null" TO "gastos_tasca_fecha_not_null"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tienda_proveedor_id_foreign" TO "gastos_tasca_proveedor_id_foreign"');
        DB::statement('ALTER TABLE "gastos_tienda" RENAME CONSTRAINT "gastos_tienda_compra_id_foreign" TO "gastos_tasca_compra_id_foreign"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tienda_proveedor_id_foreign" TO "compras_tasca_proveedor_id_foreign"');
        DB::statement('ALTER TABLE "compras_tienda" RENAME CONSTRAINT "compras_tienda_abono_usd_not_null" TO "compras_tasca_abono_usd_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_id_autorizador_foreign" TO "ventas_tasca_id_autorizador_foreign"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_id_persona_foreign" TO "ventas_tasca_id_persona_foreign"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tienda_tipo_not_null" TO "productos_tasca_tipo_not_null"');
        DB::statement('ALTER TABLE "productos_tienda" RENAME CONSTRAINT "productos_tienda_tipo_check" TO "productos_tasca_tipo_check"');
        DB::statement('ALTER TABLE "ventas_tienda_detalles" RENAME CONSTRAINT "ventas_tienda_detalles_cantidad_not_null" TO "ventas_tasca_detalles_cantidad_not_null"');
        DB::statement('ALTER TABLE "ventas_tienda" RENAME CONSTRAINT "ventas_tienda_cargo_servicio_not_null" TO "ventas_tasca_cargo_servicio_not_null"');
    }
};